on:
 schedule:
   - cron:  "20,50 0-14,23 * * *"
 workflow_dispatch:
 watch:
    types: [started]

jobs:
  sync_tailscale_latest_version:
    runs-on: ubuntu-latest
    steps:
    - name: check_latest_version
      run: |
        latest_version=$(wget -O- https://pkgs.tailscale.com/stable/ | grep tailscale_ | head -1 | cut -d'_' -f 2)
        echo "latest_version=$latest_version"  >> $GITHUB_ENV
        echo $latest_version
        
    - name: check_release_if_exist
      run: |
        code=`curl -I -m 10 -o /dev/null -s -w %{http_code} 'https://codeload.github.com/cyz0105/tailscale-openwrt/zip/refs/tags/${{ env.latest_version }}'`
        echo "code=$code"  >> $GITHUB_ENV
        echo ${{ env.http_code }}
        
    - name: download
      if: ${{ env.code }} == "404"
      run: |
        echo "下载文件"
        curl --remote-name https://pkgs.tailscale.com/stable/tailscale_${{env.latest_version}}_amd64.tgz
        curl --remote-name https://pkgs.tailscale.com/stable/tailscale_${{env.latest_version}}_arm64.tgz
        ls
        
    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: ${{ env.code }} == "404"
      with:
        tag_name: ${{env.latest_version}}
        name: ${{env.latest_version}}
        body: ${{env.latest_version}} 已从上游同步.
        draft: false
        prerelease: false
        files: |
          tailscale_${{env.latest_version}}_amd64.tgz
          tailscale_${{env.latest_version}}_arm64.tgz
        
